# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('body_text', models.TextField(db_index=True, null=True)),
                ('subject', models.CharField(default='', max_length=160)),
                ('sent', models.BooleanField(default=False)),
                ('sent_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('destination', models.EmailField(default='', max_length=254)),
            ],
        ),
    ]
