# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 12:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cyclist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hometown', models.CharField(max_length=50)),
                ('expectedAmount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('start', models.CharField(max_length=30)),
                ('end', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=320)),
                ('distanceKM', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='cyclist',
            name='legs',
            field=models.ManyToManyField(to='cyclists.Leg'),
        ),
        migrations.AddField(
            model_name='cyclist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
