# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 02:04
from __future__ import unicode_literals

import cyclists.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cyclist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetAmount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('currentPledgedAmount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('fundraising_site', models.URLField(blank=True, default='')),
                ('statement', models.TextField(blank=True, default='', max_length=1200)),
                ('picture', models.ImageField(blank=True, storage=cyclists.models.HashedURLStorage(), upload_to=cyclists.models.get_portrait_path)),
            ],
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=40)),
                ('start', models.CharField(max_length=30)),
                ('end', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, max_length=320)),
                ('duration', models.DecimalField(decimal_places=1, default=1.0, max_digits=2)),
                ('distanceKM', models.IntegerField()),
                ('morning', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='leg',
            unique_together=set([('date', 'morning')]),
        ),
        migrations.AddField(
            model_name='cyclist',
            name='legs',
            field=models.ManyToManyField(blank=True, related_name='cyclist', to='cyclists.Leg'),
        ),
        migrations.AddField(
            model_name='cyclist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
