# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 17:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyclists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cyclist',
            name='hometown',
        ),
        migrations.AlterField(
            model_name='cyclist',
            name='expectedAmount',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='cyclist',
            name='legs',
            field=models.ManyToManyField(null=True, to='cyclists.Leg'),
        ),
        migrations.AlterField(
            model_name='cyclist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
