# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cyclists', '0002_auto_20160124_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='leg',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cyclist',
            name='legs',
            field=models.ManyToManyField(to='cyclists.Leg'),
        ),
    ]
