# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20160112_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='title',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='pub_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
