# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 14:23
from __future__ import unicode_literals

from django.db import migrations
import stats.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagevisit',
            old_name='page',
            new_name='document',
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='arguments',
            field=stats.fields.DictField(default={}, editable=False),
            preserve_default=False,
        ),
    ]
