# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20160116_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='sub_document',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='document',
            field=models.CharField(default='home', max_length=80),
        ),
    ]
