# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 11:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'verbose_name': 'Opportunity', 'verbose_name_plural': 'Opportunities'},
        ),
        migrations.AddField(
            model_name='sponsor',
            name='communication_preference',
            field=models.CharField(blank=True, choices=[('email', 'email'), ('phone', 'telephone'), ('mobile', 'mobile')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in digits only - 11 digits only, no spaces.', regex='\\d+{11}')]),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='potential',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='telephone',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Full phone number must be entered - 11 digits only, no spaces or punctuation.', regex='\\d+{11}')]),
        ),
    ]
