# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sponsors', '0002_auto_20160214_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='communication_preference',
            field=models.CharField(choices=[('email', 'email'), ('phone', 'telephone'), ('mobile', 'mobile')], default='email', max_length=10),
        ),
    ]
