# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sponsors', '0004_auto_20160215_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
