# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sponsors', '0005_auto_20160220_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='company_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
