# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 11:35
from __future__ import unicode_literals

import Sponsors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sponsors', '0007_auto_20160226_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='accolade',
            field=models.TextField(blank=True, help_text='The Accolade for this sponsor once the sponsorship is agreed'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='upload_logo',
            field=models.ImageField(blank=True, upload_to=Sponsors.models.get_logo_upload_path),
        ),
    ]
