# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sponsors', '0008_auto_20160318_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='name',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='contact_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='potentials',
            field=models.ManyToManyField(blank=True, related_name='potentially_supported_by', to='Sponsors.Opportunity'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='supports',
            field=models.ManyToManyField(blank=True, related_name='supported_by', to='Sponsors.Opportunity'),
        ),
    ]
