# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import markitup.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160128_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='_content_rendered',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=markitup.fields.MarkupField(default='', no_rendered_field=True),
        ),
    ]
