# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160128_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
