# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160128_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.CharField(default='', editable=False, max_length=60, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
