# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160129_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_permanent',
            field=models.BooleanField(default=False),
        ),
    ]
