# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegisteredUsers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResetRequest',
            new_name='PasswordResetRequest',
        ),
    ]
